### ISSUE TITLE
error trying to run Instagram.py

### ISSUE THREAD

**Issue by elohim971** [Ethical-H4CK3R/Instagram#1]
Hello, 
Could you help me with that?

Traceback (most recent call last):
  File "Instagram.py", line 10, in <module>
    import socks
ImportError: No module named socks

Thank you!

**Comment by Ethical-H4CK3R** [comment]
pip install pysocks

**Comment by Ethical-H4CK3R** [comment]
Is it working now?

**Comment by elohim971** [comment]
no after pip install pysocks , I go:

Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site

**Comment by Ethical-H4CK3R** [comment]
are you using kali linux 2.0?

**Comment by fuckcia** [comment]
Dont work please help Ethical H4CK3R get the same message raceback (most recent call last):
File "Instagram.py", line 10, in 
import socks
ImportError: No module named socks

then when i type in pip install pysocks

And it comes something like this pip requirement already satisfied

**Comment by zphytonx** [comment]
I have the same problem but appears something different
Traceback (most recent call last):
  File "instagram.py", line 15, in <module>
    from Core.tor import TorManager
ImportError: No module named Core.tor
