### ISSUE TITLE
error with pass.lst

### ISSUE THREAD

**Issue by RedRockyFox** [Ethical-H4CK3R/Instagram#12]
![image](https://user-images.githubusercontent.com/32204133/30756351-bd9296ae-9fa0-11e7-84de-78b5756cf725.png)

**Comment by Ethical-H4CK3R** [comment]
It need the right path to your pass.lst file

**Comment by RedRockyFox** [comment]
but where is the pass.lst in the instagram folder?

**Comment by Ethical-H4CK3R** [comment]
You have to create it yourself; there are many ways to create it, but you can use [this script](https://github.com/Ethical-H4CK3R/PassGen)
