### ISSUE TITLE
Obtaining IP Adress.....

### ISSUE THREAD

**Issue by Fadi2003** [Ethical-H4CK3R/Instagram#14]
hello, I found your script 2 months ago, at the begening from the first time I saw it and tried it, it was working perfectly fine no errors. But now it would just get stuck at Obtaining IP Adress.. or waiting for Connection...... I saw the same issue but it was never solved. Would you be nice enough to help me, thank you for reading.

NOTE: It does not have to do anything with me internet, Ping, ms or anything else because I already tested the speed + I am on the same network as the last time when it actually worked

**Comment by Fadi2003** [comment]
![screenshot from 2017-10-15 01-35-11](https://user-images.githubusercontent.com/29684241/31583094-cc0aa3e4-b183-11e7-9df8-dd5a1230dbbb.png)

**Comment by Fadi2003** [comment]
this was after 1 hour and 27 minutes of waiting

**Comment by Ethical-H4CK3R** [comment]
Try the newer version called: [hyprPulse](https://github.com/Ethical-H4CK3R/hyprPulse)
