### ISSUE TITLE
that should be on readme.md

### ISSUE THREAD

**Issue by inficted** [Ethical-H4CK3R/Instagram#15]
![capture](https://user-images.githubusercontent.com/31377614/31674221-ef834ae6-b369-11e7-9901-3a135aaaf36e.PNG)

**Comment by ekrem0** [comment]
@inficted i think so too , but after trying to run this sofware for more than an hour , I found a actual tool that works okay , but the author does not mention about using it in windows but its available in **pip** , here is the tool https://github.com/deathsec/instagram-py , fand the good part is its well documented!
