### ISSUE TITLE
Very very slow

### ISSUE THREAD

**Issue by mojipkfr77** [Ethical-H4CK3R/Instagram#20]
your program is so slow

**Comment by Ethical-H4CK3R** [comment]
Sites like Facebook and Instagram will blacklist your IP or sue you if they notice suspicious activities from your IP. It is going slow because it uses Tor. Try [this](https://github.com/Ethical-H4CK3R/hyprPulse) program.

**Comment by mojipkfr77** [comment]
check out my program ,  i developed a instagram cracker proxyless and its so fast

**Comment by Ethical-H4CK3R** [comment]
Proxyless is a good idea. You might get arrested or sued or blacklisted, because the site will think your IP is a bot.

**Comment by Hirdyanshbhalla** [comment]
can you explain more about your proxyless script , and how to use it

**Comment by mojipkfr77** [comment]
go to my repository https://github.com/mojipkfr77/instacr

**Comment by mojipkfr77** [comment]
https://github.com/mojipkfr77/instacr

در تاریخ ۶ ژانویهٔ ۲۰۱۸ ۶:۵۹ بعدازظهر، "Hirdyanshbhalla" <
notifications@github.com> نوشت:
