### ISSUE TITLE
ImportError: No module named mechanize

### ISSUE THREAD

**Issue by TurboProgramming** [Ethical-H4CK3R/Instagram#24]
```
e210:Instagram ardacebi$ python instagram.py
Traceback (most recent call last):
  File "instagram.py", line 16, in <module>
    from Core.browser import Browser
  File "/Users/ardacebi/Instagram/Core/browser.py", line 5, in <module>
    import mechanize
ImportError: No module named mechanize
```

I know this is the second issue after closing the other one by resolving that by myself but this seems to be hard to resolve.

Why is this happening?

**Comment by Ethical-H4CK3R** [comment]
it’s not for Windows, it’s for Kali Linux

**Comment by TurboProgramming** [comment]
actually I got this error on a mac

**Comment by TurboProgramming** [comment]
I'm going to try it with kali linux but it should work with mac, right?

**Comment by Ethical-H4CK3R** [comment]
No, I wrote strictly for Kali not Mac

**Comment by Ethical-H4CK3R** [comment]
Use hyprPulse instead of this program

**Comment by jbtzx123** [comment]
Anyway I could give you an account and you try it for me? Couldn’t get it to work and looking for some reassurance.

**Comment by Tosible** [comment]
@jbtzx123 Lmfao

**Comment by mohammednawaf** [comment]
How to hack others Instagram?
