### ISSUE TITLE
lost internet connection

### ISSUE THREAD

**Issue by djbruto** [Ethical-H4CK3R/Instagram#7]
i get internet connection lost

**Comment by djbruto** [comment]
it just randomly stops about 5 passwords in and says lost internet connection

**Comment by Ethical-H4CK3R** [comment]
use https://github.com/Ethical-H4CK3R/Pulse until I get it fixed

**Comment by djbruto** [comment]
have error with pulse as well; randomly states that it solved a password to the account but it's not the correct. thanks for quick reply tho, Love your work!

**Comment by Ethical-H4CK3R** [comment]
what os are you using

**Comment by djbruto** [comment]
Kali linux 2.0 on vm

**Comment by firebreed** [comment]
I can confirm that this issue is happening and it happens randomly.
In addition, a small request; if the connection is lost, the script will continue from the last password it was using and continue from there. Or it will self-reconnection upon connection lost.

**Comment by Ethical-H4CK3R** [comment]
It does both, it will try to reconnect and try the passwords that failed to authenticate, I set it in a way where the script tries to reconnect twice before say connection lost. I can disable the connection lost feature all together if it's getting that annoying.  How long does it usually runs for before the message occurs?

**Comment by firebreed** [comment]
It varies, can be around after 30+ tries, after 300+ tries, etc. Trying to replicate the issue is quite impossible. Oh yeah, running Kali Linux 2.0 on VM as well.

**Comment by Ethical-H4CK3R** [comment]
Does the issue still occur?

**Comment by lord5522** [comment]
no it solved thanks

15 Ağustos 2017 Salı tarihinde, Ethical-H4CK3R <notifications@github.com>
yazdı:

**Comment by firebreed** [comment]
"Wait for connection" several times but never managed to re-continue/connect. Will do another test in a few hours. Will update.

**Comment by Ethical-H4CK3R** [comment]
I'll look into it.

**Comment by firebreed** [comment]
Issue confirmed, no other script(s) running except for ping -t 60 to google to see if there any line issues. Thanks for looking into it.

**Comment by firebreed** [comment]
Any logs that I can provide you so that you can troubleshoot?

**Comment by Ethical-H4CK3R** [comment]
The way I designed the script there is nothing that could be do to fix it. I would have to rewrite the entire script to fix the issue.

**Comment by T54R** [comment]
I skipped the problem of :  [-] lost connection
by commenting  some lines in the file **pulse.py**, to use my original IP address and  skipping obtaining a proxy IP address,
those lines are as follow:

![screenshot from 2017-09-18 02-22-29](https://user-images.githubusercontent.com/32045227/30525878-66821424-9bff-11e7-9b3b-1d9d9f28158d.png)



and another block before the end of **pulse.py**  file which are as follow:

![screenshot from 2017-09-18 02-23-34](https://user-images.githubusercontent.com/32045227/30525881-7469e8dc-9bff-11e7-921f-172f4e12a723.png)


hope it is useful for you friends, specially that these are my  first  words on GITHUB ;)

**Comment by firebreed** [comment]
Interesting, @T54R . I will try to have a go and report back.

**Comment by Ethical-H4CK3R** [comment]
That is not a great idea, it's a reason for my I set it to use a proxy. Either one of two things can occur if you are using your personal IP, either Facebook, Instagram, or Twitter might blacklist your IP, or they might sue you. Don't mess with those lines of code, they are the ones that are keeping you safe.

**Comment by T54R** [comment]
@Ethical-H4CK3R I connect to the proxy manually, then use the script. that what everybody should do ;)

**Comment by Ethical-H4CK3R** [comment]
manually? It a reason I made an IP manager, because if you the same ip's are being used more than a few times under a certain time, then they will not get any response.

**Comment by DesperateTurkey** [comment]
This issue also occurs to me. It spends 10 mins obtaining proxy IP then shows 'waiting for connection even though I am connected.
