### ISSUE TITLE
Can't detect tor

### ISSUE THREAD

**Issue by INN0C3N7PLA4Y3R** [Ethical-H4CK3R/Instagram#9]
I have tor but stop at 
Installing tor, please wait .......

Then

[-] please install tor

**Comment by Ethical-H4CK3R** [comment]
are you on kali? what do you see after running: which tor

**Comment by INN0C3N7PLA4Y3R** [comment]
Thanks for the replay
Its network problem and finally it  Worked

**Comment by benjamintn5** [comment]
hi Im using kali linux and when type python instagram.py username then pass list says 
installing tor,please wait...
then 
[-] please install tor 
i dont know what should i do

**Comment by Ethical-H4CK3R** [comment]
You should install tor. The script tried to do it for you, but some how failed. Check your internet connection, and try again, or run: apt-get install tor -y

**Comment by benjamintn5** [comment]
i tried t run the code but it says unable to locate package tor-y

**Comment by firebreed** [comment]
Try to install using web browser then: https://www.torproject.org/index.html.en

**Comment by benjamintn5** [comment]
I've already installed tor on my linux bit I don't why It says please install tor

**Comment by Ethical-H4CK3R** [comment]
because it is not tor-y it is tor -y. you need a space been the tor and the -y

**Comment by benjamintn5** [comment]
I did put a space between tor and -y

**Comment by 50NNY1** [comment]
hey, thanks alot for making this.
but i have tor running and working i have tested it. and yet it still wont detect tor.
![screenshot 11](https://user-images.githubusercontent.com/31995033/30492249-c6651748-9a37-11e7-877e-e69450641309.png)

**Comment by Ethical-H4CK3R** [comment]
you need tor service, not tor browser,

**Comment by 50NNY1** [comment]
so would you reccomend using something like torghost, or  4nonymizer

**Comment by inficted** [comment]
what about windows :(?

**Comment by frankenstein19** [comment]
Watch this  video guyzz this video solve your problem
https://youtu.be/3SKE1BpZfnU

**Comment by Ethical-H4CK3R** [comment]
Try the newer version called: [hyprPulse](https://github.com/Ethical-H4CK3R/hyprPulse)

**Comment by cryptec95** [comment]
what about the error in windows
